FUI.driver = {};

//** Buttons **//
//see the generating doc (docs/files/buttonNaming.ods)
FUI.driver.physicalKeys = {
	BUTTON_LBUTTON              : 0x01,
	BUTTON_RBUTTON              : 0x02,
	BUTTON_CANCEL               : 0x03,
	BUTTON_MBUTTON              : 0x04,
	BUTTON_XBUTTON1             : 0x05,
	BUTTON_XBUTTON2             : 0x06,
	//Undefined                   0x07
	BUTTON_BACK                 : 0x08,
	BUTTON_TAB                  : 0x09,
	//Reserved                    0x0A-0B
	BUTTON_CLEAR                : 0x0C,
	BUTTON_RETURN               : 0x0D,
	//Undefined                   0x0E-0F
	BUTTON_SHIFT                : 0x10,
	BUTTON_CONTROL              : 0x11,
	BUTTON_MENU                 : 0x12,
	BUTTON_PAUSE                : 0x13,
	BUTTON_CAPITAL              : 0x14,
	BUTTON_KANA                 : 0x15,
	BUTTON_HANGUEL              : 0x15,
	BUTTON_HANGUL               : 0x15,
	//Undefined                   0x16
	BUTTON_JUNJA                : 0x17,
	BUTTON_FINAL                : 0x18,
	BUTTON_HANJA                : 0x19,
	BUTTON_KANJI                : 0x19,
	//Undefined                   0x1A
	BUTTON_ESCAPE               : 0x1B,
	BUTTON_CONVERT              : 0x1C,
	BUTTON_NONCONVERT           : 0x1D,
	BUTTON_ACCEPT               : 0x1E,
	BUTTON_MODECHANGE           : 0x1F,
	BUTTON_SPACE                : 0x20,
	BUTTON_PRIOR                : 0x21,
	BUTTON_NEXT                 : 0x22,
	BUTTON_END                  : 0x23,
	BUTTON_HOME                 : 0x24,
	BUTTON_LEFT                 : 0x25,
	BUTTON_UP                   : 0x26,
	BUTTON_RIGHT                : 0x27,
	BUTTON_DOWN                 : 0x28,
	BUTTON_SELECT               : 0x29,
	BUTTON_PRINT                : 0x2A,
	BUTTON_EXECUTE              : 0x2B,
	BUTTON_SNAPSHOT             : 0x2C,
	BUTTON_INSERT               : 0x2D,
	BUTTON_DELETE               : 0x2E,
	BUTTON_HELP                 : 0x2F,
	BUTTON_0                    : 0x30,
	BUTTON_1                    : 0x31,
	BUTTON_2                    : 0x32,
	BUTTON_3                    : 0x33,
	BUTTON_4                    : 0x34,
	BUTTON_5                    : 0x35,
	BUTTON_6                    : 0x36,
	BUTTON_7                    : 0x37,
	BUTTON_8                    : 0x38,
	BUTTON_9                    : 0x39,
	//Undefined                   0x3A-40
	BUTTON_A                    : 0x41,
	BUTTON_B                    : 0x42,
	BUTTON_C                    : 0x43,
	BUTTON_D                    : 0x44,
	BUTTON_E                    : 0x45,
	BUTTON_F                    : 0x46,
	BUTTON_G                    : 0x47,
	BUTTON_H                    : 0x48,
	BUTTON_I                    : 0x49,
	BUTTON_J                    : 0x4A,
	BUTTON_K                    : 0x4B,
	BUTTON_L                    : 0x4C,
	BUTTON_M                    : 0x4D,
	BUTTON_N                    : 0x4E,
	BUTTON_O                    : 0x4F,
	BUTTON_P                    : 0x50,
	BUTTON_Q                    : 0x51,
	BUTTON_R                    : 0x52,
	BUTTON_S                    : 0x53,
	BUTTON_T                    : 0x54,
	BUTTON_U                    : 0x55,
	BUTTON_V                    : 0x56,
	BUTTON_W                    : 0x57,
	BUTTON_X                    : 0x58,
	BUTTON_Y                    : 0x59,
	BUTTON_Z                    : 0x5A,
	BUTTON_OS_LEFT              : 0x5B, // LWIN
	BUTTON_OS_RIGHT             : 0x5C, // RWIN
	BUTTON_APPS                 : 0x5D,
	//Reserved                    0x5E
	BUTTON_SLEEP                : 0x5F,
	BUTTON_NUMPAD0              : 0x60,
	BUTTON_NUMPAD1              : 0x61,
	BUTTON_NUMPAD2              : 0x62,
	BUTTON_NUMPAD3              : 0x63,
	BUTTON_NUMPAD4              : 0x64,
	BUTTON_NUMPAD5              : 0x65,
	BUTTON_NUMPAD6              : 0x66,
	BUTTON_NUMPAD7              : 0x67,
	BUTTON_NUMPAD8              : 0x68,
	BUTTON_NUMPAD9              : 0x69,
	BUTTON_MULTIPLY             : 0x6A,
	BUTTON_ADD                  : 0x6B,
	BUTTON_SEPARATOR            : 0x6C,
	BUTTON_SUBTRACT             : 0x6D,
	BUTTON_DECIMAL              : 0x6E,
	BUTTON_DIVIDE               : 0x6F,
	BUTTON_F1                   : 0x70,
	BUTTON_F2                   : 0x71,
	BUTTON_F3                   : 0x72,
	BUTTON_F4                   : 0x73,
	BUTTON_F5                   : 0x74,
	BUTTON_F6                   : 0x75,
	BUTTON_F7                   : 0x76,
	BUTTON_F8                   : 0x77,
	BUTTON_F9                   : 0x78,
	BUTTON_F10                  : 0x79,
	BUTTON_F11                  : 0x7A,
	BUTTON_F12                  : 0x7B,
	BUTTON_F13                  : 0x7C,
	BUTTON_F14                  : 0x7D,
	BUTTON_F15                  : 0x7E,
	BUTTON_F16                  : 0x7F,
	BUTTON_F17                  : 0x80,
	BUTTON_F18                  : 0x81,
	BUTTON_F19                  : 0x82,
	BUTTON_F20                  : 0x83,
	BUTTON_F21                  : 0x84,
	BUTTON_F22                  : 0x85,
	BUTTON_F23                  : 0x86,
	BUTTON_F24                  : 0x87,
	//Unassigned                  0x88-8F
	BUTTON_NUMLOCK              : 0x90,
	BUTTON_SCROLL               : 0x91,
	//OEM specific                0x92-96
	//Unassigned                  0x97-9F
	BUTTON_LSHIFT               : 0xA0,
	BUTTON_RSHIFT               : 0xA1,
	BUTTON_LCONTROL             : 0xA2,
	BUTTON_RCONTROL             : 0xA3,
	BUTTON_LMENU                : 0xA4,
	BUTTON_RMENU                : 0xA5,
	BUTTON_BROWSER_BACK         : 0xA6,
	BUTTON_BROWSER_FORWARD      : 0xA7,
	BUTTON_BROWSER_REFRESH      : 0xA8,
	BUTTON_BROWSER_STOP         : 0xA9,
	BUTTON_BROWSER_SEARCH       : 0xAA,
	BUTTON_BROWSER_FAVORITES    : 0xAB,
	BUTTON_BROWSER_HOME         : 0xAC,
	BUTTON_VOLUME_MUTE          : 0xAD,
	BUTTON_VOLUME_DOWN          : 0xAE,
	BUTTON_VOLUME_UP            : 0xAF,
	BUTTON_MEDIA_NEXT_TRACK     : 0xB0,
	BUTTON_MEDIA_PREV_TRACK     : 0xB1,
	BUTTON_MEDIA_STOP           : 0xB2,
	BUTTON_MEDIA_PLAY_PAUSE     : 0xB3,
	BUTTON_LAUNCH_MAIL          : 0xB4,
	BUTTON_LAUNCH_MEDIA_SELECT  : 0xB5,
	BUTTON_LAUNCH_APP1          : 0xB6,
	BUTTON_LAUNCH_APP2          : 0xB7,
	//Reserved                    0xB8-B9
	BUTTON_OEM_1                : 0xBA,
	BUTTON_OEM_PLUS             : 0xBB,
	BUTTON_OEM_COMMA            : 0xBC,
	BUTTON_OEM_MINUS            : 0xBD,
	BUTTON_OEM_PERIOD           : 0xBE,
	BUTTON_OEM_2                : 0xBF,
	BUTTON_OEM_3                : 0xC0,
	//Reserved                    0xC1-D7
	//Unassigned                  0xD8-DA
	BUTTON_OEM_4                : 0xDB,
	BUTTON_OEM_5                : 0xDC,
	BUTTON_OEM_6                : 0xDD,
	BUTTON_OEM_7                : 0xDE,
	BUTTON_OEM_8                : 0xDF,
	//Reserved                    0xE0
	//OEM specific                0xE1
	BUTTON_OEM_102              : 0xE2,
	//OEM specific                0xE3-E4
	BUTTON_PROCESSKEY           : 0xE5,
	//OEM specific                0xE6
	//Used to pass Unicode char.. 0xE7
	//Unassigned                  0xE8
	//OEM specific                0xE9-F5
	BUTTON_ATTN                 : 0xF6,
	BUTTON_CRSEL                : 0xF7,
	BUTTON_EXSEL                : 0xF8,
	BUTTON_EREOF                : 0xF9,
	BUTTON_PLAY                 : 0xFA,
	BUTTON_ZOOM                 : 0xFB,
	BUTTON_NONAME               : 0xFC,
	BUTTON_PA1                  : 0xFD,
	BUTTON_OEM_CLEAR            : 0xFE
};